### ISSUE TITLE
多个 Meta Description 标记

### ISSUE THREAD

**Issue by KiyanYang** [fluid-dev/hexo-theme-fluid#626]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

页面出现多个 `<meta name="description" content="……">` 标记

#### 复现步骤
该 Bug 复现步骤如下：
在任意页面查看源代码即可发现

#### 截图

- Fluid 博客主页的 HTML

  <img width="460" alt="Snipaste_2021-12-13_21-18-11" src="https://user-images.githubusercontent.com/50903774/145822804-2bd9dbc0-e763-44d5-9c32-2af995c19a48.png">

- 我的博客主页的 HTML
  
  <img width="338" alt="Snipaste_2021-12-13_21-41-51" src="https://user-images.githubusercontent.com/50903774/145823060-55812c14-e18e-4c60-b406-232fe62177a8.png">

#### 简要分析

问题可能来自 `/layout/_partial/head.ejs`，将此文件中第 26 行 https://github.com/fluid-dev/hexo-theme-fluid/blob/099445937b8b1c4fa05024bb3869b4deecd57b99/layout/_partial/head.ejs#L26 注释后的结果为：

<img width="336" alt="Snipaste_2021-12-13_21-45-10" src="https://user-images.githubusercontent.com/50903774/145823531-245db7bc-b5aa-4626-b4f9-c7457db59e4c.png">

**Comment by zkqiang** [comment]
下面的 `description` 是由 open_graph 生成的

https://github.com/hexojs/hexo/blob/ed0f239c967f35fa709581b7ec74fced5f1b5a1d/lib/plugins/helper/open_graph.js#L98-L100

所以增加了个配置防止重复
